runtime: python310  # Utilise la version de Python que tu as

entrypoint: gunicorn -b :$PORT myportfolio.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: myportfolio.settings
  SECRET_KEY: 'django-insecure-6lcq69au&_vpq@&mpc4*dx4zg6%u_++a+!-r%9ps5swv#(8zcu'
  DEBUG: 'False'

automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 3

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto
