# Generated by Django 5.1.1 on 2024-10-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name_plural': 'About me'},
        ),
    ]
