# Generated by Django 5.1.1 on 2024-10-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_aboutme_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campany_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project_title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('technical_skills', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfessionalExeperience',
        ),
    ]
