# Generated by Django 5.1.1 on 2024-10-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_professionalexperience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperience',
            name='company_logo',
            field=models.ImageField(default=1, upload_to='company_logos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='job_title',
            field=models.CharField(max_length=255),
        ),
    ]
