# Generated by Django 5.1.1 on 2024-10-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_professionalexperience_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='project_title',
            field=models.TextField(),
        ),
    ]
