# Generated by Django 5.1.1 on 2024-10-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_professionalexperience_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalskill',
            name='description',
        ),
        migrations.AlterField(
            model_name='technicalskill',
            name='icons',
            field=models.ImageField(default=1, upload_to='icons'),
            preserve_default=False,
        ),
    ]
