# Generated by Django 5.1.1 on 2024-10-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_technicalskill_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalskill',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
