# Generated by Django 5.1.1 on 2024-10-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_technicalskill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalskill',
            name='description',
            field=models.TextField(),
        ),
    ]
