# Generated by Django 5.1.1 on 2024-10-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_technicalskill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpersonalskill',
            name='skill',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='technicalskill',
            name='icons',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
    ]
