# Generated by Django 5.1.1 on 2024-10-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_professionalexperience_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='project_video',
            field=models.FileField(blank=True, null=True, upload_to='project_videos/'),
        ),
    ]
