# Generated by Django 5.1.1 on 2024-10-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='picture',
        ),
        migrations.AddField(
            model_name='project',
            name='project_video',
            field=models.FileField(blank=True, null=True, upload_to='project_videos/'),
        ),
    ]
