# Generated by Django 5.1.1 on 2024-10-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_video',
            field=models.FileField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
