# Generated by Django 5.1.1 on 2024-10-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_project_project_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_video',
            new_name='cover_image',
        ),
    ]
