# Generated by Django 5.1.1 on 2024-10-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
